services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.node
    environment:
      - NODE_ENV=production
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=tw2tracker
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    networks:
      - tw2tracker-network

  postgres:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_DB: tw2tracker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - app-data-2:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - tw2tracker-network

networks:
  tw2tracker-network:
    driver: bridge

volumes:
  app-data-2: