module.exports = {
    SYNC_SUCCESS: 'success',
    SYNC_FAIL: 'fail',
    SYNC_SUCCESS_ALL: 'sync_success_all',
    SYNC_ERROR_ALL: 'sync_error_all',
    SYNC_ERROR_SOME: 'sync_error_some',
    SYNC_ACHIEVEMENTS_SUCCESS_ALL: 'sync_achievements_success_all',
    SYNC_ACHIEVEMENTS_ERROR_ALL: 'sync_achievements_error_all',
    SYNC_ACHIEVEMENTS_ERROR_SOME: 'sync_achievements_error_some',
    SCRAPE_WORLD_START: 'scrape_world_start',
    SCRAPE_WORLD_END: 'scrape_world_end',
    SCRAPE_ALL_WORLD_START: 'scrape_all_world_start',
    SCRAPE_ALL_WORLD_END: 'scrape_all_world_end',
    IGNORE_LAST_SYNC: 'ignore_last_sync',
    SCRAPE_ACHIEVEMENT_WORLD_START: 'scrape_achievement_world_start',
    SCRAPE_ACHIEVEMENT_WORLD_END: 'scrape_achievement_world_end',
    SCRAPE_ACHIEVEMENT_ALL_WORLD_START: 'scrape_achievement_all_world_start',
    SCRAPE_ACHIEVEMENT_ALL_WORLD_END: 'scrape_achievement_all_world_end',
    REQUEST_SYNC_STATUS: 'request_sync_status'
}
